spring.application.name=kculture

# MySQL ??
spring.datasource.url=jdbc:mysql://localhost:3306/kculture
spring.datasource.username=root
spring.datasource.password=1234

# Flyway? ??? ??? ??? ??
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA? ???? ???? ?? Entity? ????? ??
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false